AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This Template will create an Amazon EC2 instance running the Amazon Linux AMI.
  It also creates an EC2 security group for the instance to give you SSH access.
  Make sure KeyName is present in AWS Account

Parameters:
  EnvironmentName:
    Description: SDLC Environment Value e.g dev/qa/prod.
    Type: String

Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: yog-1
      InstanceType: t2.micro
      ImageId: 'ami-00f7e5c52c0f43726'
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Join [ "-", [ !Ref EnvironmentName, 'ec2-security-group' ] ]
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0